//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenesTrabajo.srvOrdenesTrabajo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvOrdenesTrabajo.IOrdenesTrabajo")]
    public interface IOrdenesTrabajo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesTrabajo/DoWork", ReplyAction="http://tempuri.org/IOrdenesTrabajo/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesTrabajo/DoWork", ReplyAction="http://tempuri.org/IOrdenesTrabajo/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesTrabajo/ObtenerUsuario", ReplyAction="http://tempuri.org/IOrdenesTrabajo/ObtenerUsuarioResponse")]
        DAL.Usuario ObtenerUsuario(string user, string dominio, string contraseña, string appName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesTrabajo/ObtenerUsuario", ReplyAction="http://tempuri.org/IOrdenesTrabajo/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<DAL.Usuario> ObtenerUsuarioAsync(string user, string dominio, string contraseña, string appName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesTrabajo/ObtenerUsuariosPorParametros", ReplyAction="http://tempuri.org/IOrdenesTrabajo/ObtenerUsuariosPorParametrosResponse")]
        DAL.Usuario[] ObtenerUsuariosPorParametros(DAL.ParametrosBusqueda.ParametrosBusquedaUsuarios parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrdenesTrabajo/ObtenerUsuariosPorParametros", ReplyAction="http://tempuri.org/IOrdenesTrabajo/ObtenerUsuariosPorParametrosResponse")]
        System.Threading.Tasks.Task<DAL.Usuario[]> ObtenerUsuariosPorParametrosAsync(DAL.ParametrosBusqueda.ParametrosBusquedaUsuarios parametros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdenesTrabajoChannel : OrdenesTrabajo.srvOrdenesTrabajo.IOrdenesTrabajo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenesTrabajoClient : System.ServiceModel.ClientBase<OrdenesTrabajo.srvOrdenesTrabajo.IOrdenesTrabajo>, OrdenesTrabajo.srvOrdenesTrabajo.IOrdenesTrabajo {
        
        public OrdenesTrabajoClient() {
        }
        
        public OrdenesTrabajoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenesTrabajoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenesTrabajoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenesTrabajoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public DAL.Usuario ObtenerUsuario(string user, string dominio, string contraseña, string appName) {
            return base.Channel.ObtenerUsuario(user, dominio, contraseña, appName);
        }
        
        public System.Threading.Tasks.Task<DAL.Usuario> ObtenerUsuarioAsync(string user, string dominio, string contraseña, string appName) {
            return base.Channel.ObtenerUsuarioAsync(user, dominio, contraseña, appName);
        }
        
        public DAL.Usuario[] ObtenerUsuariosPorParametros(DAL.ParametrosBusqueda.ParametrosBusquedaUsuarios parametros) {
            return base.Channel.ObtenerUsuariosPorParametros(parametros);
        }
        
        public System.Threading.Tasks.Task<DAL.Usuario[]> ObtenerUsuariosPorParametrosAsync(DAL.ParametrosBusqueda.ParametrosBusquedaUsuarios parametros) {
            return base.Channel.ObtenerUsuariosPorParametrosAsync(parametros);
        }
    }
}
